language: objective-c
xcode_project: FoodTracker.xcodeproj
xcode_scheme: FoodTracker
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3
cache:
  directories:
  - Carthage
env:
  global:
    - FRAMEWORK_NAME=FoodTracker
  matrix:
    - DESTINATION="OS=10.3,name=iPhone 6s" SCHEME=$PROJECT SDK=iphonesimulator TEST=test
before_install:
  - gem install bundler
  - bundle install
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew outdated xctool || brew upgrade xctool
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - bundle exec danger
  - carthage bootstrap --platform iOS
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
script:
 - xcodebuild -project FoodTracker.xcodeproj -scheme FoodTracker -sdk iphonesimulator build test
